#!/usr/bin/env python3

import csv
import sys
import time
import string

networks_dictionary = dict()

MAX_NETWORKS = 10

with open (sys.argv[1], "r") as file:
    
    data = file.readlines()
    for line in data:
        vectorized_networks = line.split(",")
        for entry in vectorized_networks:
            name_data = entry.split(":")
            print(name_data[1])